[build-system]
requires = [
    "setuptools>=77.0.3",
    "torch>=2.10.0",
    "ninja"
]
build-backend = "setuptools.build_meta"

# the limited abi should support multiple python versions
# do not build free-threaded versions because they will not work
[tool.cibuildwheel]
build = "cp310-manylinux_*"
skip = "cp3??t-*"

[tool.cibuildwheel.linux]
# Tells auditwheel to skip trying to bundle or locate PyTorch core binaries
manylinux-x86_64-image = "manylinux_2_28"
# might need to change for gpu builds
environment = { PIP_EXTRA_INDEX_URL = "https://download.pytorch.org/whl/cpu" }
repair-wheel-command = "auditwheel repair --exclude libc10.so --exclude libtorch.so --exclude libtorch_cpu.so --exclude libtorch_python.so -w {dest_dir} {wheel}"

[project]
name = "hirschberg-viterbi"
version = "0.1.0"
description = "Memory-efficient forced alignment for long sequences."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
authors = [
    {name = "Lawry Sorenson", email = "lawrysorenson@byu.edu"}
]
dependencies = [
    "build>=1.6.1",
    "torch>=2.10.0",
    "twine>=7.0.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: POSIX :: Linux"
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["hirschberg_viterbi*"]
exclude = ["tests*"]

[dependency-groups]
dev = [
    "numpy>=2.2.6",
    "torchaudio>=2.11.0",
]

[project.urls]
Homepage = "https://github.com/byu-matrix-lab/hirschberg-viterbi"
Issues = "https://github.com/byu-matrix-lab/hirschberg-viterbi/issues"
